include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "/nix/store/"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

linter:
  rules:
    prefer_single_quotes: true
    avoid_void_async: true
    unawaited_futures: true
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
